### ISSUE TITLE
Error when trying to run web server locally

### ISSUE THREAD

**Issue by americodls** [unfazedEgnimadevspace/Gracker#8]
When I try to run `bin/dev` I get this error:

```
17:34:55 css.1  | Rebuilding...
17:34:55 css.1  | Error: Cannot find module 'flowbite/plugin'
17:34:55 css.1  | Require stack:
17:34:55 css.1  | - /Users/americo/Gracker/config/tailwind.config.js
17:34:55 css.1  | - /snapshot/tailwindcss/lib/cli/build/plugin.js
17:34:55 css.1  | - /snapshot/tailwindcss/lib/cli/build/index.js
17:34:55 css.1  | - /snapshot/tailwindcss/lib/cli/index.js
17:34:55 css.1  | - /snapshot/tailwindcss/lib/cli.js
17:34:55 css.1  | - /snapshot/tailwindcss/standalone-cli/standalone.js
17:34:55 css.1  | 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
17:34:55 css.1  |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
17:34:55 css.1  |     at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
17:34:55 css.1  |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
17:34:55 css.1  |     at Module.require (node:internal/modules/cjs/loader:1005:19)
17:34:55 css.1  |     at Module.require (pkg/prelude/bootstrap.js:1855:31)
17:34:55 css.1  |     at Module.require (/snapshot/tailwindcss/standalone-cli/standalone.js:26:22)
17:34:55 css.1  |     at require (node:internal/modules/cjs/helpers:102:18)
17:34:55 css.1  |     at Object.<anonymous> (/Users/americo/Gracker/config/tailwind.config.js:22:5)
17:34:55 css.1  |     at Module._compile (node:internal/modules/cjs/loader:1105:14)
17:34:55 css.1  |     at Module._compile (pkg/prelude/bootstrap.js:1894:32) {
17:34:55 css.1  |   code: 'MODULE_NOT_FOUND',
17:34:55 css.1  |   requireStack: [
17:34:55 css.1  |     '/Users/americo/Gracker/config/tailwind.config.js',
17:34:55 css.1  |     '/snapshot/tailwindcss/lib/cli/build/plugin.js',
17:34:55 css.1  |     '/snapshot/tailwindcss/lib/cli/build/index.js',
17:34:55 css.1  |     '/snapshot/tailwindcss/lib/cli/index.js',
17:34:55 css.1  |     '/snapshot/tailwindcss/lib/cli.js',
17:34:55 css.1  |     '/snapshot/tailwindcss/standalone-cli/standalone.js'
17:34:55 css.1  |   ],
17:34:55 css.1  |   pkg: true
17:34:55 css.1  | }
```

**Comment by unfazedEgnimadevspace** [comment]
I think you need to run 'npm install flowbite ' , it's a tailwind css plug in building  the user interface

**Comment by americodls** [comment]
Understood.

As software developers, we should always think about being productive.
And part of being productive is our capacity of eliminating repetitive tasks.

Imagine that anyone, including ourselves that wants to set up this project, will run into this problem and need to search for a solution and fix it.

We can do better than that.

Ruby on rails project structure already brings to us the file `bin/setup` that should be our project setup script. All a new developer should do is clone the repository and run that script to have the project running locally.

I recommend you read that file carefully to understand the steps are necessary to set up the application locally.

After that, I would suggest that we update that file so that it solves the setup problems for us.

I think we can add the command to install `flowbite` via `npm` right after the `bundle install` in that file.

**Comment by americodls** [comment]
I also recommend adding `/node_modules/` to the file `.gitignore`, to prevent us to push js source files to our remote repo.
